// ================================================== navbar ===========================================================
document.writeln("<nav class=\"fixed-navbar\">");
document.writeln("        <a href=\"fishhome.html\">");
document.writeln("            <img src=\"images/logo1.png\" class=\"logo\">&nbsp;家长教育焦虑研究小组");
document.writeln("        </a>");
document.writeln("        <ul>");
document.writeln("            <li class=\"has-submenu\">");
document.writeln("                <a href=\"fishhome.html\">主页</a>");
document.writeln("            </li>");
document.writeln("");
document.writeln("            <li class=\"has-submenu team\">");
document.writeln("                <a href=\"fishresearch.html\">问题提出</a>");
document.writeln("                <ul class=\"submenu\">");
document.writeln("                    <li><a href=\"fishresearch.html\">问题研究</a></li>");
document.writeln("                    <li><a href=\"fishpaper.html\">文献综述</a>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("");
document.writeln("            <li class=\"has-submenu project\">");
document.writeln("                <a href=\"fishpre_questionnaire.html\">成果展示</a>");
document.writeln("                <ul class=\"submenu\">");
document.writeln("                    <li><a href=\"fishpre_questionnaire.html\">家长教育焦虑水平分析</a></li>");
document.writeln("                    <li><a href=\"fishmodel.html\">访谈分析与结论</a></li>");
document.writeln("                    <li><a href=\"fishquestionnaire.html\">调查问卷</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("");
document.writeln("            <li class=\"has-submenu handbook\">");
document.writeln("                <a href=\"fish1handbook.html\">宣传实录</a>");
document.writeln("                <ul class=\"submenu\">");
document.writeln("                    <li><a href=\"fish1handbook.html\">隐秘的补习焦虑的父母</a></li>");
document.writeln("                    <li><a href=\"fish2handbook.html\">很多父母<br>看不得孩子快乐</a></li>");
document.writeln("                    <li><a href=\"fish3handbook.html\">培养自信开朗的孩子</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("");
document.writeln("            <li class=\"has-submenu team\">");
document.writeln("                <a href=\"fishteam.html\">关于我们</a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("");
document.writeln("        <!-- <form class=\"d-flex\" style=\"vertical-align:middle;margin-left:20px;margin-right:30px\">");
document.writeln("            <input class=\"form-control me-2\" type=\"search\" placeholder=\"输入关键词进行搜索\" aria-label=\"Search\">");
document.writeln("            <button class=\"btn btn-outline-success\" type=\"submit\">搜索</button>");
document.writeln("        </form> -->");
document.writeln("    </nav>");